function testCSV = importfile_test_data(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   TESTCSV = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   TESTCSV = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   testCSV = importfile1('testCSV.csv', 2, 8001);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/05/23 15:23:07

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
%	column5: double (%f)
%   column6: double (%f)
%	column7: double (%f)
%   column8: double (%f)
%	column9: double (%f)
%   column10: double (%f)
%	column11: double (%f)
%   column12: double (%f)
%	column13: double (%f)
%   column14: double (%f)
%	column15: double (%f)
%   column16: double (%f)
%	column17: double (%f)
%   column18: double (%f)
%	column19: double (%f)
%   column20: double (%f)
%	column21: double (%f)
%   column22: double (%f)
%	column23: double (%f)
%   column24: double (%f)
%	column25: double (%f)
%   column26: double (%f)
%	column27: double (%f)
%   column28: double (%f)
%	column29: double (%f)
%   column30: double (%f)
%	column31: double (%f)
%   column32: double (%f)
%	column33: double (%f)
%   column34: double (%f)
%	column35: double (%f)
%   column36: double (%f)
%	column37: double (%f)
%   column38: double (%f)
%	column39: double (%f)
%   column40: double (%f)
%	column41: double (%f)
%   column42: double (%f)
%	column43: double (%f)
%   column44: double (%f)
%	column45: double (%f)
%   column46: double (%f)
%	column47: double (%f)
%   column48: double (%f)
%	column49: double (%f)
%   column50: double (%f)
%	column51: double (%f)
%   column52: double (%f)
%	column53: double (%f)
%   column54: double (%f)
%	column55: double (%f)
%   column56: double (%f)
%	column57: double (%f)
%   column58: double (%f)
%	column59: double (%f)
%   column60: double (%f)
%	column61: double (%f)
%   column62: double (%f)
%	column63: double (%f)
%   column64: double (%f)
%	column65: double (%f)
%   column66: double (%f)
%	column67: double (%f)
%   column68: double (%f)
%	column69: double (%f)
%   column70: double (%f)
%	column71: double (%f)
%   column72: double (%f)
%	column73: double (%f)
%   column74: double (%f)
%	column75: double (%f)
%   column76: double (%f)
%	column77: double (%f)
%   column78: double (%f)
%	column79: double (%f)
%   column80: double (%f)
%	column81: double (%f)
%   column82: double (%f)
%	column83: double (%f)
%   column84: double (%f)
%	column85: double (%f)
%   column86: double (%f)
%	column87: double (%f)
%   column88: double (%f)
%	column89: double (%f)
%   column90: double (%f)
%	column91: double (%f)
%   column92: double (%f)
%	column93: double (%f)
%   column94: double (%f)
%	column95: double (%f)
%   column96: double (%f)
%	column97: double (%f)
%   column98: double (%f)
%	column99: double (%f)
%   column100: double (%f)
%	column101: double (%f)
%   column102: double (%f)
%	column103: double (%f)
%   column104: double (%f)
%	column105: double (%f)
%   column106: double (%f)
%	column107: double (%f)
%   column108: double (%f)
%	column109: double (%f)
%   column110: double (%f)
%	column111: double (%f)
%   column112: double (%f)
%	column113: double (%f)
%   column114: double (%f)
%	column115: double (%f)
%   column116: double (%f)
%	column117: double (%f)
%   column118: double (%f)
%	column119: double (%f)
%   column120: double (%f)
%	column121: double (%f)
%   column122: double (%f)
%	column123: double (%f)
%   column124: double (%f)
%	column125: double (%f)
%   column126: double (%f)
%	column127: double (%f)
%   column128: double (%f)
%	column129: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
testCSV = table(dataArray{1:end-1}, 'VariableNames', {'x1','x2','x3','x4','x5','x6','x7','x8','x9','x10','x11','x12','x13','x14','x15','x16','x17','x18','x19','x20','x21','x22','x23','x24','x25','x26','x27','x28','x29','x30','x31','x32','x33','x34','x35','x36','x37','x38','x39','x40','x41','x42','x43','x44','x45','x46','x47','x48','x49','x50','x51','x52','x53','x54','x55','x56','x57','x58','x59','x60','x61','x62','x63','x64','x65','x66','x67','x68','x69','x70','x71','x72','x73','x74','x75','x76','x77','x78','x79','x80','x81','x82','x83','x84','x85','x86','x87','x88','x89','x90','x91','x92','x93','x94','x95','x96','x97','x98','x99','x100','x101','x102','x103','x104','x105','x106','x107','x108','x109','x110','x111','x112','x113','x114','x115','x116','x117','x118','x119','x120','x121','x122','x123','x124','x125','x126','x127','x128'});

